parameters:
#    gma_site.example.class: Gma\SiteBundle\Example

services:
#    gma_site.example:
#        class: %gma_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
